name: 'bristol_air_quality'
version: '1.0.0'
config-version: 2

# This name must match the profile name in profiles.yml
profile: 'bristol_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bristol_air_quality:
    staging:
      +materialized: view
    marts:
      +materialized: table
    queries:
      +materialized: table
