#!/usr/bin/env python3
"""
Developer DX Script: Prepare and Bootstrap Dagster Cloud Code Location (Hybrid Model).
Automates Docker building, tagging, registry pushing, and dagster_cloud.yaml generation.
"""

import sys
import subprocess
import shutil
from pathlib import Path

def check_docker_installed():
    """Verify that the Docker daemon CLI is installed and running."""
    if not shutil.which("docker"):
        print("[-] Error: Docker CLI is not installed or not in PATH.", file=sys.stderr)
        print("    Please install Docker Desktop to proceed.", file=sys.stderr)
        sys.exit(1)
    
    try:
        subprocess.run(["docker", "info"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        print("[-] Error: Docker daemon is not running.", file=sys.stderr)
        print("    Please start Docker Desktop and try again.", file=sys.stderr)
        sys.exit(1)

def run_command(cmd, description):
    """Execute shell commands, streaming output directly to the terminal."""
    print(f"\n[*] Running: {description}...")
    print(f"    Command: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True)
        print(f"[+] Success: {description} completed.")
    except subprocess.CalledProcessError as e:
        print(f"[-] Error: {description} failed.", file=sys.stderr)
        print(f"    Exit code: {e.returncode}", file=sys.stderr)
        sys.exit(e.returncode)

def generate_dagster_cloud_yaml(image_name):
    """Write the dagster_cloud.yaml file into the root of the project."""
    root_dir = Path(__file__).resolve().parent.parent
    yaml_path = root_dir / "dagster_cloud.yaml"
    
    content = f"""# ==============================================================================
# Dagster Cloud Configuration - Hybrid Code Location
# ==============================================================================
# Automatically generated by scripts/prep_dagster_cloud.py
# Registered locations will compile and materialize inside your private network.

locations:
  - location_name: bristol-air-quality-pipeline
    image: {image_name}
    code_source:
      package_name: dagster_orch
"""
    
    with open(yaml_path, "w") as f:
        f.write(content)
    
    print(f"\n[+] Created: {yaml_path.name} in project root.")
    print("    Code location details:")
    print(f"    - Location Name: bristol-air-quality-pipeline")
    print(f"    - Container Image: {image_name}")

def get_docker_username():
    """Attempt to resolve the user's Docker username from .env config."""
    root_dir = Path(__file__).resolve().parent.parent
    env_path = root_dir / ".env"
    if env_path.exists():
        try:
            with open(env_path, "r") as f:
                for line in f:
                    if line.strip().startswith("DOCKER_USERNAME="):
                        val = line.split("DOCKER_USERNAME=")[1].strip().strip('"').strip("'")
                        if val:
                            return val
        except Exception:
            pass
    return None

def main():
    print("===============================================================================")
    print("      Dagster Cloud Onboarding & Container Registry Prep Utility              ")
    print("===============================================================================")
    
    check_docker_installed()
    
    # 1. Gather Registry Information
    print("\n--- 1. Registry Details ---")
    docker_user = get_docker_username()
    default_registry = f"docker.io/{docker_user}" if docker_user else ""
    
    if default_registry:
        registry = input(f"Enter your Docker Registry / Repository Name\n(default: {default_registry}): ").strip()
        if not registry:
            registry = default_registry
    else:
        registry = input("Enter your Docker Registry / Repository Name\n(e.g. docker.io/username or ECR registry URL): ").strip()
        if not registry:
            print("[-] Error: Registry name cannot be empty.", file=sys.stderr)
            sys.exit(1)
        
    image_repo = input("Enter the Repository Name (default: bristol-air-pipeline): ").strip()
    if not image_repo:
        image_repo = "bristol-air-pipeline"
        
    tag = input("Enter Image Tag (default: latest): ").strip()
    if not tag:
        tag = "latest"
        
    # Clean registry format (remove trailing slashes)
    registry = registry.rstrip("/")
    full_image_name = f"{registry}/{image_repo}:{tag}"
    
    print(f"\nTarget Container Registry Image:\n>>> {full_image_name}")
    
    # 2. Build Docker Image
    print("\n--- 2. Build Container ---")
    build_cmd = [
        "docker", "build",
        "-t", f"{image_repo}:{tag}",
        "-f", "docker/Dockerfile.pipeline",
        "."
    ]
    run_command(build_cmd, "Docker image build")
    
    # 3. Tag Docker Image
    print("\n--- 3. Tag Container ---")
    tag_cmd = [
        "docker", "tag",
        f"{image_repo}:{tag}",
        full_image_name
    ]
    run_command(tag_cmd, f"Tagging image to registry format")
    
    # 4. Generate dagster_cloud.yaml
    print("\n--- 4. Configure Code Location ---")
    generate_dagster_cloud_yaml(full_image_name)
    
    # 5. Push to Registry
    print("\n--- 5. Publish to Registry ---")
    push_prompt = input("Do you want to push the container to the remote registry now? (y/n): ").strip().lower()
    if push_prompt == "y":
        push_cmd = ["docker", "push", full_image_name]
        print("\nNote: Please make sure you ran 'docker login' before choosing 'y'.")
        run_command(push_cmd, f"Pushing image to remote registry")
    else:
        print("\n[i] Skipped: Docker push skipped. You can manually push using:")
        print(f"    docker push {full_image_name}")
        
    print("\n===============================================================================")
    print("[+] Preparation Successful!")
    print("    Follow docs/deployment/dagster_cloud.md to start your local hybrid agent.")
    print("===============================================================================")

if __name__ == "__main__":
    main()
