name: Confluence GitOps Sync

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  confluence-sync:
    name: Sync docs to Confluence Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Sync Markdown to Confluence
        uses: martinsalerno/github-to-confluence-action@v4
        with:
          confluence-base-url: 'https://uwe-bristol-air.atlassian.net/wiki'
          confluence-api-token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-username: ${{ secrets.CONFLUENCE_EMAIL }}
          confluence-space-key: ${{ secrets.CONFLUENCE_SPACE_KEY }}
          confluence-parent-page-id: ${{ secrets.CONFLUENCE_PARENT_PAGE_ID }}
          markdown-root: docs
